### ISSUE TITLE
Breeze exits and errors silently with windows_subsystem

### ISSUE THREAD

**Issue by mchangrh** [zedseven/breeze#1]
When breeze is launched without arguments or when a file is missing, it exits correctly but errors are missing, even when launched from the terminal. 

This seems to have been caused by https://github.com/zedseven/breeze/commit/fe9eda87 as when the line is removed, breeze outputs the error correctly to the terminal. Even with that line removed, I did not see any terminal output when breeze was launched via double click, dragging `example.sent` to the exe or when launched from the terminal.

**Comment by zedseven** [comment]
Yep, I'm aware of this issue. Unfortunately, it requires a bit more research on my part, and I haven't gotten to it yet.

I think the way I might avoid this (or at least make it more user-friendly) is to display the error *as a presentation* in-app if something is wrong with the presentation file. This would reduce the dependence upon the CLI, and avoid Windows' nonsense.

Relevant upstream issues:
- rust-lang/rust#109038
- rust-lang/rust#67159

**Comment by zedseven** [comment]
> Even with that line removed, I did not see any terminal output when breeze was launched via double click, dragging `example.sent` to the exe or when launched from the terminal.

You didn't see a black console window pop up at all? It might have been hidden behind the main program. I saw it regularly during my testing on Windows, and it's known Windows behaviour due to backwards-compatibility. :/

**Comment by mchangrh** [comment]
> > Even with that line removed, I did not see any terminal output when breeze was launched via double click, dragging `example.sent` to the exe or when launched from the terminal.
> 
> You didn't see a black console window pop up at all? It might have been hidden behind the main program. I saw it regularly during my testing on Windows, and it's known Windows behaviour due to backwards-compatibility. :/

I tried finding it as a subprocess in task manager, Win and Alt-tabbing but couldn't find the black window. A presentation for the error would probably be best, either way.

**Comment by zedseven** [comment]
As of v1.1.0, user errors are shown using the presentation interface.

There may be more that can be done with the console issue on Windows, but this doesn't have much of a CLI, and it should be much less necessary to see console output now.
As a result, I'm closing this issue for the time-being.
